language: ruby
rvm:
  - 2.4.1

script:
  # first dump all the remote content as local files
  - gem install bundler:1.17.3
  - bundle exec jekyll build
  # then generate the website
  # - bundle exec dato jekyll build


# env:
#   global:
#     - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_ACCESS_KEY
  bucket: dieaffenschaukel.de
  local_dir: _site
  acl: public_read
  skip_cleanup: true  
  # on:
  #   repo: paulHempel/nicos-blog
  region: eu-central-1

after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_ID -s $AWS_SECRET_ID -c $CF_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
# exclude: [vendor]