language: ruby
rvm:
  - 2.7.1

before_script:
  - gem install bundler:2.1.4
  - bundle update --bundler

script:
  - bundle exec jekyll build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_ACCESS_KEY
  bucket: dieaffenschaukel.de
  local_dir: _site
  acl: public_read
  skip_cleanup: true
  region: eu-central-1