# Site
title:              Affenschaukel
bio:                'Ich bin ein Affe der gerne schreibt'
description:        "Der affengeilste Blog im ganzen Netz!"
locale:             ger
url:                "die-affenschaukel.de"


defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# gems:
#   - jekyll-paginate-v2
    
# Pagination Settings
# pagination:
#   enabled: true
#   per_page: 7
#   offset: 0
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
